### ISSUE TITLE
Heated Floor Area

### ISSUE THREAD

**Issue by asaee** [NRCan-IETS-CE-O-HBC/HTAP#43]
getHeatedFloorArea function estimates the heated floor area and compare that with the user-input data. 

A few concerns about area calculations using ceiling area as a reference: 
(Heated floor area = Ceiling area * No of Storeys + Slab area)

1. The cathedral ceiling area is the actual area, not the horizontal projection of the ceiling area. 
2. It is possible that the user-input ceiling area is not consistent with the building geometry (too small or too large)
3. Does the slab attribute accounts for the slab area in basement/heated crawl space?
4. xml format has slightly changed in v11.5b8.

**Comment by jblake59** [comment]
Committed changes that improved the GetHeatedFloorArea function. Notes on each request above:

1. Did not project cathedral ceiling area to the horizontal since the XML output field used does not identify the components of ceiling area. Could switch from using this XML output field to a different approach later.
2. Quite possible but have no solution
3. Changed logic to use new XML output for basement slab area
4. Accounted for this change.
